spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: weather
  jackson:
    time-zone: Asia/Shanghai
server:
  port: 9522




